name: Run Bash and Python scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Bash script
      run: ./show_date_israel.sh

    - name: Run Python palindrome script
      run: python3 palindrome.py
