name: Docker Command Test

on: push

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "Hello World"

      - name: Check Docker version
        run: docker -v

